### ISSUE TITLE
Put isCallable/isConstructable on Function/Object instead of Reflect

### ISSUE THREAD

**Issue by Jamesernator** [caitp/TC39-Proposals#4]
I just thought I'd note this given that the committee seems to be firmly decided that only Proxy traps will appear on Reflect and this proposal is explicitly mentioned [here](https://github.com/jasnell/proposal-istypes/issues/14).

The simplest solution would seem to be just to place these on Function or Object.

---

Alternatively it could be possible to also add `isCallable`/`isConstructable` as traps to Proxy so that objects could actually become callable e.g.:

```js
const p = new Proxy({}, {
    isCallable() { return true },
    apply() { return 3 }
})

console.log(p()) // 3
```

I'm not sure what `typeof` would do to such objects though.

**Comment by ExE-Boss** [comment]
> Alternatively it could be possible to also add `isCallable`/`isConstructable` as traps to Proxy so that objects could actually become callable

That&nbsp;won't&nbsp;work, as&nbsp;an&nbsp;object is&nbsp;callable when&nbsp;it&nbsp;has [the&nbsp;`[[Call]]` internal&nbsp;method](https://tc39.es/ecma262/#sec-ecmascript-function-objects-call-thisargument-argumentslist), which&nbsp;can't&nbsp;be&nbsp;added/removed&nbsp;willy‑nilly, same&nbsp;with [the&nbsp;`[[Construct]]` internal&nbsp;method](https://tc39.es/ecma262/#sec-ecmascript-function-objects-construct-argumentslist-newtarget), which&nbsp;constructors&nbsp;have in&nbsp;addition to&nbsp;`[[Call]]`.

---

So&nbsp;the&nbsp;only&nbsp;option is&nbsp;to&nbsp;move these&nbsp;static&nbsp;methods to&nbsp;the&nbsp;`Function`&nbsp;constructor:

```webidl
[NonEnumerableMethods]
partial interface Function {
	static boolean isCallable(object foo);
	static boolean isConstructor(object foo);
};
```

**Comment by bathos** [comment]
To help illustrate what @ExE-Boss is talking about with regard to those hypothetical traps: if the (internal) isConstructor and isCallable ops ceased to be side-effect free and ceased to have invariant results, a _lot_ of stuff would be broken unless it were also changed to account for it — not just within other ES algorithms, but also in Web IDL, HTML, etc. And I’m pretty sure it would cause big trouble for SES.

**Comment by caitp** [comment]
I think this discussion has been settled
